version: "3.7"
networks:
  internal:
    name: du-capstone
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.17.0.0/16
services:
  api:
    image: du-capstone/api
    networks:
      - internal
    ports:
      - "4000:4000"
  site:
    image: du-capstone/frontend
    ports:
      - "80:3000"